const navList = [
    {
        title:"商品",
        path:"/product",
        children:[
            {
                title:"商品1",
                path:"/product1"
            },
            {
                title:"商品2",
                path:"/product2"
            },
            {
                title:"商品3",
                path:"/product3",
                children:[
                    {
                        title:"商品31",
                        path:"/product31"
                    },
                    {
                        title:"商品32",
                        path:"/product32"
                    },
                ]
            },
            
        ]
    },
    {
        title:"用户",
        path:"/user"
    },
    {
        title:"管理",
        path:"/manager"
    },
    {
        title:"添加",
        path:"/add",
        children:[
            {
                title:"添加1",
                path:"/add11"
            },
            {
                title:"添加2",
                path:"/add12"
            },
        ]
    },
    {
        title:"减少",
        path:"/minus"
    },
]
export default navList;